spring:
  application:
    name: llm-service
  datasource:
    url: jdbc:mysql://localhost:3306/llm_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    ollama:
      base-url: http://enjay.myds.me:11434
      chat:
        model: qwen3:14b
        options:
          temperature: 0.6
          top-p: 0.95
          top-k: 20
          min-p: 0
  docker:
    compose:
      enabled: true
debug: true
